### ISSUE TITLE
Support Documenting APIs with Swagger

### ISSUE THREAD

**Issue by kogisin** [cosmostation/mintscan-binance-dex-backend#10]
## Summary

Having a meaningful documentation of APIs is important for other users; however, this is not an imminent issue right now. This feature will be supported later.

Generate Swagger docs for Documenting Mintscan APIs.

**Comment by kala0427** [comment]
HI
Do you have any experience in using mintscan api?
I don't know about it very well, and I am trying to find the api to get contract abi from its address or something.
In etherscan, it provides the endpoint to do it, but I don't know if mintscan has the same api.
If you have any idea or advice, please help me.
